[general]
live_config_reload = true
[window]
decorations = "full"
opacity = 0.7
blur = true
padding = { x = 10, y = 10 }
[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular"}
[mouse]
hide_when_typing = true
[scrolling]
history= 20000

